BOARD_CELLS = [
    {
        "index": 0,
        "name": "Start",
        "cell_type": "start",
        "description": "Collect your starting bonus when you pass this cell.",
        "amount": 200,
    },
    {
        "index": 1,
        "name": "Copper Hollow",
        "cell_type": "property",
        "description": "A modest neighborhood with steady rent.",
        "price": 60,
        "color_group": "brown",
    },
    {
        "index": 2,
        "name": "Community Fund",
        "cell_type": "community",
        "description": "Draw a helpful or risky community card.",
    },
    {
        "index": 3,
        "name": "Harbor Avenue",
        "cell_type": "property",
        "description": "Busy port-side property with rising value.",
        "price": 60,
        "color_group": "brown",
    },
    {
        "index": 4,
        "name": "City Tax",
        "cell_type": "tax",
        "description": "Pay a fixed tax to the bank.",
        "amount": 200,
    },
    {
        "index": 5,
        "name": "North Line",
        "cell_type": "railroad",
        "description": "Fast travel route across the city.",
        "price": 200,
    },
    {
        "index": 6,
        "name": "Juniper Street",
        "cell_type": "property",
        "description": "Quiet suburban homes with low entry cost.",
        "price": 100,
        "color_group": "light_blue",
    },
    {
        "index": 7,
        "name": "Chance",
        "cell_type": "chance",
        "description": "Draw a surprise card and adapt.",
    },
    {
        "index": 8,
        "name": "Maple Street",
        "cell_type": "property",
        "description": "A growing street with affordable upgrades.",
        "price": 100,
        "color_group": "light_blue",
    },
    {
        "index": 9,
        "name": "Cedar Street",
        "cell_type": "property",
        "description": "Popular family block near the park.",
        "price": 120,
        "color_group": "light_blue",
    },
    {
        "index": 10,
        "name": "Jail",
        "cell_type": "jail",
        "description": "Just visiting for now.",
    },
    {
        "index": 11,
        "name": "Amber Alley",
        "cell_type": "property",
        "description": "An artsy district with higher rent.",
        "price": 140,
        "color_group": "pink",
    },
    {
        "index": 12,
        "name": "Power Works",
        "cell_type": "utility",
        "description": "Public utility with dynamic pricing later on.",
        "price": 150,
    },
    {
        "index": 13,
        "name": "Birch Boulevard",
        "cell_type": "property",
        "description": "Tree-lined avenue with solid traffic.",
        "price": 140,
        "color_group": "pink",
    },
    {
        "index": 14,
        "name": "Ash Avenue",
        "cell_type": "property",
        "description": "A polished location close to downtown.",
        "price": 160,
        "color_group": "pink",
    },
    {
        "index": 15,
        "name": "East Line",
        "cell_type": "railroad",
        "description": "Connects neighborhoods on the east side.",
        "price": 200,
    },
    {
        "index": 16,
        "name": "Coral Court",
        "cell_type": "property",
        "description": "A bright block with rising interest.",
        "price": 180,
        "color_group": "orange",
    },
    {
        "index": 17,
        "name": "Community Fund",
        "cell_type": "community",
        "description": "Another community card awaits.",
    },
    {
        "index": 18,
        "name": "Pearl Place",
        "cell_type": "property",
        "description": "Shops and apartments packed together.",
        "price": 180,
        "color_group": "orange",
    },
    {
        "index": 19,
        "name": "Driftwood Drive",
        "cell_type": "property",
        "description": "A scenic route by the water.",
        "price": 200,
        "color_group": "orange",
    },
    {
        "index": 20,
        "name": "Free Parking",
        "cell_type": "free_parking",
        "description": "A breather before the next lap.",
    },
    {
        "index": 21,
        "name": "Willow Walk",
        "cell_type": "property",
        "description": "Calm streets with dependable demand.",
        "price": 220,
        "color_group": "red",
    },
    {
        "index": 22,
        "name": "Chance",
        "cell_type": "chance",
        "description": "A risky card could change the round.",
    },
    {
        "index": 23,
        "name": "Elm Estate",
        "cell_type": "property",
        "description": "A valuable neighborhood near the station.",
        "price": 220,
        "color_group": "red",
    },
    {
        "index": 24,
        "name": "Oak Square",
        "cell_type": "property",
        "description": "Central location with premium traffic.",
        "price": 240,
        "color_group": "red",
    },
    {
        "index": 25,
        "name": "South Line",
        "cell_type": "railroad",
        "description": "The southern rail route stays busy.",
        "price": 200,
    },
    {
        "index": 26,
        "name": "River Street",
        "cell_type": "property",
        "description": "Popular destination for weekend visitors.",
        "price": 260,
        "color_group": "yellow",
    },
    {
        "index": 27,
        "name": "Market Plaza",
        "cell_type": "property",
        "description": "Shopping district with solid upside.",
        "price": 260,
        "color_group": "yellow",
    },
    {
        "index": 28,
        "name": "Water Works",
        "cell_type": "utility",
        "description": "The city water network.",
        "price": 150,
    },
    {
        "index": 29,
        "name": "Garden Gate",
        "cell_type": "property",
        "description": "A polished entrance to a wealthy block.",
        "price": 280,
        "color_group": "yellow",
    },
    {
        "index": 30,
        "name": "Go To Jail",
        "cell_type": "go_to_jail",
        "description": "Move directly to jail when rules are active.",
    },
    {
        "index": 31,
        "name": "Sunset Strip",
        "cell_type": "property",
        "description": "Evening crowds make this area valuable.",
        "price": 300,
        "color_group": "green",
    },
    {
        "index": 32,
        "name": "Rose Row",
        "cell_type": "property",
        "description": "Stylish address with premium upgrades.",
        "price": 300,
        "color_group": "green",
    },
    {
        "index": 33,
        "name": "Community Fund",
        "cell_type": "community",
        "description": "One more card draw for the table.",
    },
    {
        "index": 34,
        "name": "Kingfisher Quay",
        "cell_type": "property",
        "description": "Elite waterfront real estate.",
        "price": 320,
        "color_group": "green",
    },
    {
        "index": 35,
        "name": "West Line",
        "cell_type": "railroad",
        "description": "The last major rail connection.",
        "price": 200,
    },
    {
        "index": 36,
        "name": "Chance",
        "cell_type": "chance",
        "description": "Late-game surprise card.",
    },
    {
        "index": 37,
        "name": "Moonstone Mile",
        "cell_type": "property",
        "description": "Prestige location with very high demand.",
        "price": 350,
        "color_group": "dark_blue",
    },
    {
        "index": 38,
        "name": "Luxury Tax",
        "cell_type": "tax",
        "description": "Pay an extra premium tax.",
        "amount": 100,
    },
    {
        "index": 39,
        "name": "Skyline View",
        "cell_type": "property",
        "description": "Top-tier property with the best view in town.",
        "price": 400,
        "color_group": "dark_blue",
    },
]


if len(BOARD_CELLS) != 40:
    raise RuntimeError("BOARD_CELLS must contain exactly 40 cells.")


def get_board_cells() -> list[dict]:
    return [cell.copy() for cell in BOARD_CELLS]

